### ISSUE TITLE
OpenClinica 3.17 slow loading

### ISSUE THREAD

**Issue by samaramaiden** [OpenClinica/OpenClinica#3658]
I have installed the latest distribution and noticed the instance is super slow and not fully loading icons.
OC 3.17, Tomcat 9.0.80, OpenJDK8U_64x_win_hotspot_8u382b05, Postgres 11.21

Any help appreciated. The logs have been displaying like below.

Catalina.log:
```
14-Sep-2023 15:00:56.243 WARNING [main] liquibase.parser.null Current XML parsers seems to not support EntityResolver2. External entities won't be correctly loaded
14-Sep-2023 15:00:58.112 WARNING [main] liquibase.parser.null Current XML parsers seems to not support EntityResolver2. External entities won't be correctly loaded
```

tomcat9_stdout.log:
```
-ERROR in ch.qos.logback.classic.net.SyslogAppender[SYSLOG-USAGESTATS] - Could not create SyslogWriter java.net.UnknownHostException: usage.openclinica.com
	at java.net.UnknownHostException: usage.openclinica.com
	at 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:867)
	at 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at 	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
	at 	at java.net.InetAddress.getAllByName0(InetAddress.java:1291)
	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1144)
	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1065)
	at 	at java.net.InetAddress.getByName(InetAddress.java:1015)
	at 	at ch.qos.logback.core.net.SyslogOutputStream.<init>(SyslogOutputStream.java:44)
	at 	at ch.qos.logback.classic.net.SyslogAppender.createOutputStream(SyslogAppender.java:61)
	at 	at ch.qos.logback.core.net.SyslogAppenderBase.start(SyslogAppenderBase.java:54)
	at 	at ch.qos.logback.classic.net.SyslogAppender.start(SyslogAppender.java:51)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.akaza.openclinica.dao.core.OCContextLoaderListener.<init>(OCContextLoaderListener.java:15)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at 	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
	at 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4389)
	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662)
	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1023)
	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1910)
	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:824)
	at 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:474)
	at 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617)
	at 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318)
	at 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
	at 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
	at 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
	at 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
	at 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:922)
	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
	at 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
```

tomcat9_stderr.log:
```
14-Sep-2023 15:03:51.194 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [354051] milliseconds
com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 4: The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.readSyndFeedFromStream(HttpURLFeedFetcher.java:272)
	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.getSyndFeedFromStream(HttpURLFeedFetcher.java:277)
	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.resetFeedInfo(HttpURLFeedFetcher.java:191)
	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveAndCacheFeed(HttpURLFeedFetcher.java:163)
	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveFeed(HttpURLFeedFetcher.java:119)
	at org.akaza.openclinica.control.RssReaderServlet.getFeed(RssReaderServlet.java:58)
	at org.akaza.openclinica.control.RssReaderServlet.doGet(RssReaderServlet.java:48)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.akaza.openclinica.control.core.OCServletFilter.doFilter(OCServletFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:217)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.akaza.openclinica.web.filter.LocaleFilter.doFilter(LocaleFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.jdom.input.JDOMParseException: Error on line 4: The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:504)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:888)
	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:194)
	... 54 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 292; The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
	... 56 more
```

**Comment by Minhjka** [comment]
> Tôi đã cài đặt bản phân phối mới nhất và nhận thấy phiên bản này siêu chậm và không tải đầy đủ các biểu tượng. OC 3.17, Tomcat 9.0.80, OpenJDK8U_64x_win_hotspot_8u382b05, Postgres 11.21
> 
> Bất kỳ trợ giúp nào được đánh giá cao. Các nhật ký đã được hiển thị như dưới đây.
> 
> Catalina.log:
> 
> ```
> 14-Sep-2023 15:00:56.243 WARNING [main] liquibase.parser.null Current XML parsers seems to not support EntityResolver2. External entities won't be correctly loaded
> 14-Sep-2023 15:00:58.112 WARNING [main] liquibase.parser.null Current XML parsers seems to not support EntityResolver2. External entities won't be correctly loaded
> ```
> 
> tomcat9_stdout.log:
> 
> ```
> -ERROR in ch.qos.logback.classic.net.SyslogAppender[SYSLOG-USAGESTATS] - Could not create SyslogWriter java.net.UnknownHostException: usage.openclinica.com
> 	at java.net.UnknownHostException: usage.openclinica.com
> 	at 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> 	at 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:867)
> 	at 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
> 	at 	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:815)
> 	at 	at java.net.InetAddress.getAllByName0(InetAddress.java:1291)
> 	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1144)
> 	at 	at java.net.InetAddress.getAllByName(InetAddress.java:1065)
> 	at 	at java.net.InetAddress.getByName(InetAddress.java:1015)
> 	at 	at ch.qos.logback.core.net.SyslogOutputStream.<init>(SyslogOutputStream.java:44)
> 	at 	at ch.qos.logback.classic.net.SyslogAppender.createOutputStream(SyslogAppender.java:61)
> 	at 	at ch.qos.logback.core.net.SyslogAppenderBase.start(SyslogAppenderBase.java:54)
> 	at 	at ch.qos.logback.classic.net.SyslogAppender.start(SyslogAppender.java:51)
> 	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
> 	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
> 	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
> 	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
> 	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
> 	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
> 	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
> 	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
> 	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
> 	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
> 	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
> 	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
> 	at 	at org.akaza.openclinica.dao.core.OCContextLoaderListener.<init>(OCContextLoaderListener.java:15)
> 	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at 	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:143)
> 	at 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4389)
> 	at 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4914)
> 	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
> 	at 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
> 	at 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662)
> 	at 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1023)
> 	at 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1910)
> 	at 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
> 	at 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:824)
> 	at 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:474)
> 	at 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617)
> 	at 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318)
> 	at 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:114)
> 	at 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:402)
> 	at 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:345)
> 	at 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:893)
> 	at 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795)
> 	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
> 	at 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
> 	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
> 	at 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
> 	at 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249)
> 	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
> 	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:922)
> 	at 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
> 	at 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
> 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
> 	at 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
> ```
> 
> tomcat9_stderr.log:
> 
> ```
> 14-Sep-2023 15:03:51.194 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [354051] milliseconds
> com.sun.syndication.io.ParsingFeedException: Invalid XML: Error on line 4: The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
> 	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:198)
> 	at com.sun.syndication.io.SyndFeedInput.build(SyndFeedInput.java:123)
> 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.readSyndFeedFromStream(HttpURLFeedFetcher.java:272)
> 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.getSyndFeedFromStream(HttpURLFeedFetcher.java:277)
> 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.resetFeedInfo(HttpURLFeedFetcher.java:191)
> 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveAndCacheFeed(HttpURLFeedFetcher.java:163)
> 	at com.sun.syndication.fetcher.impl.HttpURLFeedFetcher.retrieveFeed(HttpURLFeedFetcher.java:119)
> 	at org.akaza.openclinica.control.RssReaderServlet.getFeed(RssReaderServlet.java:58)
> 	at org.akaza.openclinica.control.RssReaderServlet.doGet(RssReaderServlet.java:48)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.akaza.openclinica.control.core.OCServletFilter.doFilter(OCServletFilter.java:45)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:217)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.akaza.openclinica.web.filter.LocaleFilter.doFilter(LocaleFilter.java:39)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
> 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1790)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: org.jdom.input.JDOMParseException: Error on line 4: The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
> 	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:504)
> 	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:888)
> 	at com.sun.syndication.io.WireFeedInput.build(WireFeedInput.java:194)
> 	... 54 more
> Caused by: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 292; The reference to entity "gform.scriptsLoaded" must end with the ';' delimiter.
> 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 	at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
> 	... 56 more
> ```

Hi Sam
Have you run the website yet? I installed it but I can't even access the website interface. Can you help me install?

**Comment by PurnenduMondal** [comment]
I solved this issue by following steps after I complete the installation steps [here](https://github.com/OpenClinica/OpenClinica/wiki/Install-OpenClinica-3.16-on-Windows-(DRAFT-IN-REVISION))
1. Open it intellij IDEA (I used trial version)
2. Go to Run -> Edit Configuration -> click on + -> search and select TomCat Server Local
3. Click on Configure in Server Tab-> add the tomcat 9 folder directory. e.g C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0
4. Click on Deployment Tab -> click on + -> select all one by one. e.g. OpenClinica-web:war, OpenClinica-web:war exploded, OpenClinica-ws:war, OpenClinica-ws:war exploded. Note: If you don't see your artifact listed, you may need to build it first (Build -> Build Artifacts... -> Build).
5. Now open this location in cmd OpenClinica\ws\src\main\webapp\WEB-INF\schemas. for each .xsd file. run xjc filename.xsd. for example `xjc crf.xsd`. this will create the org folder
6. move the openclinica folder from OpenClinica\ws\src\main\webapp\WEB-INF\schemas\org to OpenClinica\ws\src\main\java\org
7. Copy C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\openclinica.config\datainfo.properties file to core/src/main/resources folder
8. Now Click on Run
9. Copy all file and replace C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica_web_war to C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica and OpenClinica_ws_war 
10. Now access the url http://localhost:8080/OpenClinica/

**Comment by Minhjka** [comment]
> I solved this issue by following steps after I complete the installation steps [here](https://github.com/OpenClinica/OpenClinica/wiki/Install-OpenClinica-3.16-on-Windows-(DRAFT-IN-REVISION))
> 
> 1. Open it intellij IDEA (I used trial version)
> 2. Go to Run -> Edit Configuration -> click on + -> search and select TomCat Server Local
> 3. Click on Configure in Server Tab-> add the tomcat 9 folder directory. e.g C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0
> 4. Click on Deployment Tab -> click on + -> select all one by one. e.g. OpenClinica-web:war, OpenClinica-web:war exploded, OpenClinica-ws:war, OpenClinica-ws:war exploded. Note: If you don't see your artifact listed, you may need to build it first (Build -> Build Artifacts... -> Build).
> 5. Now open this location in cmd OpenClinica\ws\src\main\webapp\WEB-INF\schemas. for each .xsd file. run xjc filename.xsd. for example `xjc crf.xsd`. this will create the org folder
> 6. move the openclinica folder from OpenClinica\ws\src\main\webapp\WEB-INF\schemas\org to OpenClinica\ws\src\main\java\org
> 7. Copy C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\openclinica.config\datainfo.properties file to core/src/main/resources folder
> 8. Now Click on Run
> 9. Copy all file and replace C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica_web_war to C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica and OpenClinica_ws_war
> 10. Now access the url http://localhost:8080/OpenClinica/
Thank you PurnenduMondal
  I followed the steps you instructed but in step 5 I did not see the path OpenClinica\ws\src\main\webapp\WEB-INF\ . Can you give me more specific instructions?

**Comment by amdk2011** [comment]
I can provide you services to install the openclinica on windows/linux enviorment. Please contact me via [amdk2011@gmail.com](mailto:amdk2011@gmail.com)
