### ISSUE TITLE
Unable to start 3.17

### ISSUE THREAD

**Issue by CGarces** [OpenClinica/OpenClinica#3659]
I'm using OpenClinic  3.17 with:

- tomcat-9.0.80 
- openjdk version "1.8.0_382"
- CentOS Linux 7

I can't deploy the webapp.
I have set the log level to debug inside OpenClinica but I not see specific app logs, just the ones from tomcat.

<details><summary>The first stat trace at catalina.out show this:
</summary>
<p>

15-Sep-2023 01:12:24.985 SEVERE [main] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [/usr/local/apache-tomcat-9.0.80/webapps/OpenClinica]
        java.lang.IllegalStateException: Error starting child
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:686)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:658)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662)
                at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1184)
                at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1932)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
...
        Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/OpenClinica]]
                at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:419)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:186)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683)
                ... 37 more
        Caused by: java.lang.NullPointerException
                at org.apache.tomcat.util.descriptor.tld.TldResourcePath.openStream(TldResourcePath.java:124)
                at org.apache.tomcat.util.descriptor.tld.TldParser.parse(TldParser.java:62)
</p>
</details>

<details><summary>OpenClinica-ws also fails but looks like is a different issue:
</summary>
<p>

15-Sep-2023 01:12:24.987 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/apache-tomcat-9.0.80/webapps/OpenClinica-ws]
15-Sep-2023 01:12:29.847 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.IllegalArgumentException: Circular variable reference detected while parsing input [${log.dir} --> ${log.dir}]
        at ch.qos.logback.core.subst.NodeToStringTransformer.handleVariable(NodeToStringTransformer.java:85)
        at ch.qos.logback.core.subst.NodeToStringTransformer.compileNode(NodeToStringTransformer.java:72)
        at ch.qos.logback.core.subst.NodeToStringTransformer.handleVariable(NodeToStringTransformer.java:97)
        at ch.qos.logback.core.subst.NodeToStringTransformer.compileNode(NodeToStringTransformer.java:72)
        at ch.qos.logback.core.subst.NodeToStringTransformer.transform(NodeToStringTransformer.java:60)
        at ch.qos.logback.core.subst.NodeToStringTransformer.substituteVariable(NodeToStringTransformer.java:48)
        at ch.qos.logback.core.util.OptionHelper.substVars(OptionHelper.java:117)
</p>
</details>

Any clue?

**Comment by samaramaiden** [comment]
I am having the same problem. On Jira they said OC3.17 works with Pg15. So I did all the installs but OC doesn't start. 
I even tried downloading up to date jdbc driver 42.6 because one of the msgs said the encryption was having issues. So I assumed it was because Pg15 uses SHAM instead of MD5, and I didn't want to downgrade Pg security back to MD5. I ALTER the user postgres so it could be re-created using SHAM, but it didn't solve the issue.

**Comment by amdk2011** [comment]
I can provide you services to install the openclinica on windows enviorment. Please contact me via [amdk2011@gmail.com](mailto:amdk2011@gmail.com)

**Comment by PurnenduMondal** [comment]
I solved this issue by following steps after I complete the installation steps [here](https://github.com/OpenClinica/OpenClinica/wiki/Install-OpenClinica-3.16-on-Windows-(DRAFT-IN-REVISION))
1. Open it intellij IDEA (I used trial version)
2. Go to Run -> Edit Configuration -> click on + -> search and select TomCat Server Local
3. Click on Configure in Server Tab-> add the tomcat 9 folder directory. e.g C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0
4. Click on Deployment Tab -> click on + -> select all one by one. e.g. OpenClinica-web:war, OpenClinica-web:war exploded, OpenClinica-ws:war, OpenClinica-ws:war exploded. Note: If you don't see your artifact listed, you may need to build it first (Build -> Build Artifacts... -> Build).
5. Now open this location in cmd OpenClinica\ws\src\main\webapp\WEB-INF\schemas. for each .xsd file. run xjc filename.xsd. for example `xjc crf.xsd`. this will create the org folder
6. move the openclinica folder from OpenClinica\ws\src\main\webapp\WEB-INF\schemas\org to OpenClinica\ws\src\main\java\org
7. Copy C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\openclinica.config\datainfo.properties file to core/src/main/resources folder
8. Now Click on Run
9. Copy all file and replace C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica_web_war to C:\Program Files (x86)\Apache Software Foundation\Tomcat 9.0\webapps\OpenClinica and OpenClinica_ws_war 
10. Now access the url http://localhost:8080/OpenClinica/

**Comment by amdk2011** [comment]
Dear Punendu,
Great & Congratulations. Thanks for sharing.

Thanks & Regards,
Danish

**Comment by amdk2011** [comment]
I can provide you services to install the openclinica on windows/linux enviorment. Please contact me via [amdk2011@gmail.com](mailto:amdk2011@gmail.com)

**Comment by JV-coder** [comment]
I'm having trouble starting openclinica. Hopefully the steps can get corrected because it doesn't work as documented. Alot of wasted time on my part.

**Comment by JV-coder** [comment]
@PurnenduMondal can I screen share with you to open my program? @amdk2011 your email  amdk2011@gmail.com is full.
