### ISSUE TITLE
I can't deploy open clinica

### ISSUE THREAD

**Issue by yaiselpm** [OpenClinica/OpenClinica#994]
When i start the tomcat server in the tomcat7-stedrr its show me the next error and can't deploy the openclinica project
2017-09-15 10:44:35 Commons Daemon procrun stderr initialized
sep 15, 2017 11:44:36 AM org.apache.catalina.core.AprLifecycleListener init
Información: La biblioteca nativa de Apache Tomcat basada en ARP que permite un rendimiento óptimo en entornos de desarrollo no ha sido hallada en java.library.path: C:\Program Files\Apache Software Foundation\Tomcat 7.0\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;.
sep 15, 2017 11:44:37 AM org.apache.catalina.startup.HostConfig deployDirectory
Información: Despliegue del directorio C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\docs de la aplicación web
sep 15, 2017 11:44:37 AM org.apache.catalina.startup.HostConfig deployDirectory
Información: Despliegue del directorio C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\manager de la aplicación web
sep 15, 2017 11:44:37 AM org.apache.catalina.startup.HostConfig deployDirectory
Información: Despliegue del directorio C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\OpenClinica de la aplicación web
sep 15, 2017 11:44:41 AM org.apache.catalina.loader.WebappClassLoader validateJarFile
Información: validateJarFile(C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\OpenClinica\WEB-INF\lib\servlet-api-2.3.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
sep 15, 2017 11:44:59 AM org.apache.catalina.startup.TaglibUriRule body
Información: TLD skipped. URI: http://code.google.com/p/jmesa is already defined
sep 15, 2017 11:45:24 AM org.apache.catalina.core.StandardContext startInternal
Grave: Error listenerStart
sep 15, 2017 11:45:24 AM org.apache.catalina.core.StandardContext startInternal
Grave: Falló en arranque del Contexto [/OpenClinica] debido a errores previos
sep 15, 2017 11:45:24 AM org.apache.catalina.startup.HostConfig deployDirectory
Información: Despliegue del directorio C:\Program Files\Apache Software Foundation\Tomcat 7.0\webapps\ROOT de la aplicación web
sep 15, 2017 11:45:24 AM org.apache.coyote.AbstractProtocol start
Información: Starting ProtocolHandler ["http-bio-8080"]
sep 15, 2017 11:45:24 AM org.apache.coyote.AbstractProtocol start
Información: Starting ProtocolHandler ["ajp-bio-8009"]
sep 15, 2017 11:45:24 AM org.apache.catalina.startup.Catalina start
Información: Server startup in 47199 ms
towireCapableBeanFactory.java:394)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:353)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:983)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:879)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1325)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1086)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:626)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
	at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
	at org.akaza.openclinica.dao.core.OCContextLoaderListener.contextInitialized(OCContextLoaderListener.java:38)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:632)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1229)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by frissner** [comment]
unfortunately your stacktrace is incomplete.
i'd recommed to start from scratch
1. reinstall tomcat (optional if you are sure to have a fully working tomcat instance)
2. expand oc.war-file to subdirectory in ${webapps}
3. check in ${webapps}/${OC-Instance}/WEB-INF/classes/datainfo.properties
  * database configuration
  * filepath
  * sysurl
  * logging configuration
4. restart tomcat

**Comment by amdk2011** [comment]
I can provide you services to install the openclinica 3.17. Please contact me via [amdk2011@gmail.com](mailto:amdk2011@gmail.com)
